# Generated by Django 5.0.3 on 2024-06-18 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DoctorPatientFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Age (years)')),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (0, 'Female')], default=1, verbose_name='Sex')),
                ('cp', models.IntegerField(choices=[(1, 'Typical Angina'), (2, 'Atypical Angina'), (3, 'Non-Anginal Pain'), (4, 'Asymptomatic')], verbose_name='Chest Pain Type')),
                ('trestbps', models.IntegerField(verbose_name='Resting Blood Pressure (mm Hg) on admission to the hospital')),
                ('chol', models.FloatField(verbose_name='Total Serum Cholesterol (mg/dl)')),
                ('fbs', models.IntegerField(choices=[(1, 'True'), (0, 'False')], default=1, verbose_name='Fasting Blood Sugar > 120 mg/dl?')),
                ('restecg', models.IntegerField(choices=[(0, 'Normal'), (1, 'Abnormal - ST-T wave'), (2, 'Abnormal - Left Ventricular Hypertrophy')], verbose_name='Resting Electrocardiographic Results')),
                ('thalach', models.IntegerField(verbose_name='Maximum Heart Rate Achieved')),
                ('exang', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='Exercise Induced Angina?')),
                ('oldpeak', models.FloatField(verbose_name='ST Depression Induced by Exercise Relative to Rest')),
                ('slope', models.IntegerField(choices=[(1, 'Upsloping'), (2, 'Flat'), (3, 'Downsloping')], verbose_name='Slope of the Peak Exercise ST Segment')),
                ('ca', models.FloatField(verbose_name='Number of Major Vessels (0-3) Colored by Fluoroscopy')),
                ('thal', models.IntegerField(choices=[(3, 'Normal'), (6, 'Fixed Defect'), (7, 'Reversible Defect')], verbose_name='Thalassemia')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Electrocardiogram (ECG)')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Echocardiogram')),
                ('diagnosis', models.CharField(max_length=255)),
                ('prognosis', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_files', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to='users.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientFile',
        ),
    ]
