# Generated by Django 5.0.6 on 2024-06-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_patient_doctor_doctorpatientfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpatientfile',
            name='image',
        ),
        migrations.AddField(
            model_name='doctorpatientfile',
            name='dat_file',
            field=models.FileField(blank=True, null=True, upload_to='ecg/input/', verbose_name='ECG_dat'),
        ),
        migrations.AddField(
            model_name='doctorpatientfile',
            name='image_ii',
            field=models.ImageField(blank=True, null=True, upload_to='ecg/output/', verbose_name='ECG_ii'),
        ),
        migrations.AddField(
            model_name='doctorpatientfile',
            name='image_v6',
            field=models.ImageField(blank=True, null=True, upload_to='ecg/output/', verbose_name='ECG_v6'),
        ),
        migrations.AddField(
            model_name='doctorpatientfile',
            name='image_vz',
            field=models.ImageField(blank=True, null=True, upload_to='ecg/output/', verbose_name='ECG_vz)'),
        ),
    ]
