# Generated by Django 5.0.6 on 2024-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_doctorpatientfile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorpatientfile',
            old_name='diagnosis',
            new_name='rf_diagnosis',
        ),
        migrations.AddField(
            model_name='doctorpatientfile',
            name='ecg_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientfile',
            name='final_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='prognosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
