# Generated by Django 5.0.6 on 2024-06-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_diagnosis_doctorpatientfile_rf_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='rf_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
