# Generated by Django 5.0.6 on 2024-06-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctorpatientfile_rf_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientfile',
            name='echo_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age (years)'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='ca',
            field=models.FloatField(blank=True, null=True, verbose_name='Number of Major Vessels (0-3) Colored by Fluoroscopy'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='chol',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Serum Cholesterol (mg/dl)'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='cp',
            field=models.IntegerField(blank=True, choices=[(1, 'Typical Angina'), (2, 'Atypical Angina'), (3, 'Non-Anginal Pain'), (4, 'Asymptomatic')], null=True, verbose_name='Chest Pain Type'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='exang',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], default=0, null=True, verbose_name='Exercise Induced Angina?'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='fbs',
            field=models.IntegerField(blank=True, choices=[(1, 'True'), (0, 'False')], default=1, null=True, verbose_name='Fasting Blood Sugar > 120 mg/dl?'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='oldpeak',
            field=models.FloatField(blank=True, null=True, verbose_name='ST Depression Induced by Exercise Relative to Rest'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='restecg',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Abnormal - ST-T wave'), (2, 'Abnormal - Left Ventricular Hypertrophy')], null=True, verbose_name='Resting Electrocardiographic Results'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (0, 'Female')], default=1, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='slope',
            field=models.IntegerField(blank=True, choices=[(1, 'Upsloping'), (2, 'Flat'), (3, 'Downsloping')], null=True, verbose_name='Slope of the Peak Exercise ST Segment'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='thal',
            field=models.IntegerField(blank=True, choices=[(3, 'Normal'), (6, 'Fixed Defect'), (7, 'Reversible Defect')], null=True, verbose_name='Thalassemia'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='thalach',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Heart Rate Achieved'),
        ),
        migrations.AlterField(
            model_name='doctorpatientfile',
            name='trestbps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resting Blood Pressure (mm Hg) on admission to the hospital'),
        ),
    ]
